import Day02.input
import Day02.toCommand

fun main() {

    val commands = input.map { it.toCommand() }

    val answer1 = commands.fold(0 to 0) { (ax, ay), n ->
        when (n.direction) {
            "down" -> ax to ay + n.distance
            "up" -> ax to ay - n.distance
            else -> ax + n.distance to ay
        }
    }.let { (x, y) -> x * y }

    println(answer1) // 1690020

    val answer2 = commands.fold(listOf(0, 0, 0)) { acc, n ->
        when (n.direction) {
            "down" -> listOf(acc[0], acc[1], acc[2] + n.distance)
            "up" -> listOf(acc[0], acc[1], acc[2] - n.distance)
            else -> listOf(acc[0] + n.distance, acc[1] + acc[2] * n.distance, acc[2])
        }
    }.let { (x, y) -> x * y }

    println(answer2) // 1408487760
}

object Day02 {

    data class Command(val direction: String, val distance: Int)

    fun String.toCommand() = split(' ').let { (dir, dist) -> Command(dir, dist.toInt()) }

    val input: List<String> = """
        forward 4
        down 8
        down 8
        up 2
        up 7
        forward 5
        forward 5
        up 7
        down 6
        down 3
        down 1
        forward 5
        forward 9
        up 2
        down 9
        forward 4
        up 5
        forward 7
        down 2
        forward 7
        down 2
        forward 4
        up 3
        down 9
        up 8
        down 2
        down 6
        up 1
        forward 3
        down 6
        down 2
        forward 9
        up 1
        forward 5
        down 1
        forward 2
        up 2
        forward 4
        down 3
        down 8
        up 2
        down 3
        up 4
        down 8
        forward 7
        forward 9
        down 7
        down 1
        forward 5
        up 3
        down 6
        down 6
        forward 1
        down 9
        forward 6
        forward 9
        forward 2
        forward 5
        forward 7
        down 1
        up 6
        up 7
        forward 8
        forward 6
        forward 2
        down 5
        up 3
        up 4
        down 9
        up 4
        down 9
        up 4
        down 5
        forward 3
        down 8
        up 2
        down 2
        forward 7
        down 7
        forward 6
        down 2
        forward 5
        down 1
        forward 9
        down 9
        down 5
        forward 2
        forward 3
        forward 6
        forward 1
        down 8
        forward 2
        forward 1
        forward 9
        down 8
        forward 8
        up 1
        up 2
        forward 2
        forward 7
        down 2
        up 9
        forward 5
        forward 5
        up 5
        down 1
        up 8
        forward 3
        up 5
        forward 2
        up 8
        up 7
        forward 4
        down 6
        up 1
        up 6
        forward 5
        down 8
        forward 4
        down 7
        forward 5
        down 4
        down 9
        forward 2
        down 5
        down 2
        down 3
        forward 8
        down 8
        down 2
        down 5
        down 6
        up 8
        down 1
        up 7
        up 4
        up 1
        up 6
        forward 6
        forward 6
        forward 8
        up 5
        forward 4
        forward 5
        forward 3
        down 8
        forward 9
        forward 6
        forward 6
        up 1
        up 8
        forward 2
        up 9
        down 1
        up 7
        up 3
        down 3
        forward 2
        down 5
        up 8
        forward 3
        up 5
        down 3
        down 3
        up 7
        forward 2
        forward 3
        forward 6
        forward 9
        up 3
        forward 1
        up 9
        down 8
        forward 5
        down 8
        forward 9
        down 1
        forward 7
        forward 9
        forward 2
        down 6
        up 6
        down 2
        down 1
        forward 7
        down 3
        forward 3
        down 3
        forward 1
        forward 6
        forward 1
        down 4
        down 4
        down 5
        forward 3
        forward 1
        up 8
        forward 7
        down 6
        up 6
        down 5
        up 6
        down 3
        down 8
        down 9
        forward 2
        up 8
        forward 1
        forward 2
        forward 7
        forward 5
        up 6
        down 9
        up 9
        forward 7
        forward 6
        forward 7
        down 8
        down 6
        forward 5
        down 2
        down 5
        down 3
        down 4
        up 5
        down 5
        forward 7
        forward 2
        down 1
        forward 6
        up 8
        down 3
        down 5
        down 3
        forward 3
        up 2
        forward 9
        forward 2
        up 4
        down 3
        down 7
        forward 9
        forward 6
        up 1
        up 2
        down 5
        up 8
        forward 9
        forward 2
        down 3
        down 6
        up 3
        down 9
        down 2
        up 4
        down 3
        up 7
        forward 3
        up 9
        down 3
        down 9
        down 1
        down 1
        forward 7
        down 9
        forward 3
        up 6
        down 8
        down 3
        forward 7
        forward 1
        up 4
        forward 8
        forward 1
        forward 9
        up 9
        forward 4
        up 2
        down 6
        down 5
        down 8
        down 2
        down 4
        forward 5
        down 8
        down 1
        forward 5
        forward 9
        down 4
        forward 5
        forward 4
        forward 4
        up 6
        down 7
        down 2
        forward 8
        down 7
        forward 7
        forward 7
        forward 3
        down 3
        forward 6
        down 5
        down 5
        forward 3
        down 7
        up 3
        up 6
        forward 8
        down 3
        down 6
        forward 5
        forward 4
        down 4
        down 3
        down 1
        down 4
        down 2
        forward 1
        forward 5
        down 9
        forward 8
        down 7
        forward 4
        down 5
        down 5
        forward 7
        forward 9
        down 5
        down 8
        up 9
        forward 1
        down 9
        up 1
        down 8
        forward 4
        up 8
        up 7
        down 4
        forward 2
        forward 9
        up 9
        forward 4
        forward 5
        forward 5
        forward 4
        forward 4
        down 8
        forward 3
        forward 3
        forward 1
        forward 7
        forward 7
        up 2
        forward 9
        down 8
        forward 3
        down 3
        down 3
        down 4
        forward 9
        forward 9
        forward 7
        forward 9
        down 6
        forward 6
        down 4
        forward 7
        down 3
        forward 2
        down 9
        down 9
        up 2
        down 7
        down 6
        up 5
        forward 6
        forward 5
        down 9
        forward 8
        down 9
        forward 9
        down 7
        up 8
        forward 5
        forward 1
        down 5
        forward 1
        down 4
        up 6
        up 1
        down 5
        forward 3
        down 1
        up 7
        down 8
        up 5
        down 8
        up 6
        forward 6
        down 8
        up 2
        forward 5
        down 5
        down 7
        down 7
        forward 8
        forward 6
        forward 2
        forward 3
        forward 3
        forward 9
        down 7
        up 8
        up 1
        forward 8
        down 5
        down 7
        forward 2
        down 9
        down 5
        down 5
        forward 6
        forward 1
        forward 8
        down 3
        down 3
        down 7
        up 3
        down 3
        down 5
        down 1
        forward 3
        forward 2
        forward 4
        forward 1
        forward 3
        forward 6
        down 6
        down 4
        forward 2
        down 8
        up 1
        down 7
        down 6
        down 3
        down 6
        forward 8
        up 7
        down 7
        up 7
        down 1
        forward 2
        forward 9
        up 8
        down 2
        down 3
        down 7
        down 2
        up 2
        down 1
        down 7
        up 6
        down 4
        forward 9
        down 8
        down 1
        forward 5
        forward 1
        up 7
        up 9
        up 9
        down 5
        down 7
        down 2
        down 6
        down 3
        forward 8
        forward 4
        up 3
        down 9
        up 3
        down 6
        up 8
        forward 7
        down 7
        up 5
        down 1
        down 3
        up 4
        forward 2
        down 7
        down 3
        down 7
        up 1
        forward 8
        down 3
        forward 7
        down 8
        forward 5
        forward 8
        down 8
        up 4
        up 8
        forward 3
        down 7
        up 6
        down 9
        forward 4
        forward 4
        forward 3
        up 4
        down 4
        down 7
        forward 6
        down 7
        down 8
        up 5
        down 4
        up 6
        up 6
        up 4
        down 7
        forward 7
        up 4
        down 2
        up 2
        forward 6
        down 5
        down 1
        forward 2
        up 1
        down 4
        up 2
        down 7
        down 5
        up 5
        forward 6
        up 2
        forward 2
        up 9
        up 4
        down 1
        down 3
        up 7
        up 5
        down 9
        down 2
        forward 9
        down 1
        up 9
        down 4
        down 8
        forward 3
        forward 1
        forward 4
        forward 9
        down 5
        down 5
        down 8
        up 4
        up 1
        down 9
        up 4
        forward 9
        up 1
        forward 7
        down 4
        up 2
        down 1
        forward 9
        down 9
        down 2
        forward 8
        up 2
        forward 6
        down 1
        up 9
        down 3
        down 2
        down 8
        down 2
        forward 8
        forward 2
        forward 8
        down 3
        up 6
        forward 5
        forward 4
        forward 7
        forward 1
        down 8
        forward 7
        down 9
        up 7
        up 5
        forward 1
        down 6
        down 6
        up 9
        up 9
        up 1
        forward 1
        forward 5
        up 1
        forward 2
        down 8
        up 9
        forward 2
        forward 8
        down 2
        up 5
        up 9
        down 5
        forward 2
        forward 4
        forward 2
        up 7
        down 9
        forward 5
        down 1
        down 6
        up 1
        forward 8
        down 1
        down 7
        up 2
        forward 4
        down 2
        up 6
        forward 6
        forward 3
        down 3
        forward 2
        down 2
        up 9
        forward 2
        up 1
        down 9
        down 4
        up 8
        forward 3
        down 9
        down 9
        forward 9
        forward 8
        up 8
        down 8
        up 8
        forward 4
        down 9
        up 5
        forward 8
        up 6
        forward 7
        up 6
        down 2
        down 3
        forward 9
        forward 5
        down 6
        forward 9
        down 5
        down 9
        down 7
        down 9
        down 3
        forward 4
        forward 2
        down 2
        down 7
        down 7
        up 2
        up 3
        forward 6
        up 7
        forward 4
        down 3
        forward 2
        down 1
        down 8
        forward 5
        down 3
        up 9
        forward 2
        forward 7
        down 4
        forward 1
        forward 8
        forward 9
        forward 5
        down 4
        up 3
        up 9
        forward 6
        forward 4
        forward 9
        down 3
        forward 1
        forward 9
        down 9
        down 5
        forward 9
        forward 4
        down 3
        down 9
        down 5
        up 6
        up 5
        forward 5
        up 8
        down 3
        forward 7
        up 3
        forward 9
        down 8
        forward 2
        forward 1
        forward 9
        down 9
        forward 1
        down 6
        forward 7
        up 3
        forward 7
        up 3
        down 1
        forward 5
        forward 5
        up 3
        forward 2
        down 3
        forward 8
        up 9
        forward 7
        down 7
        forward 5
        up 4
        forward 8
        down 1
        up 4
        down 2
        forward 2
        down 5
        down 5
        up 2
        forward 1
        down 3
        down 8
        forward 6
        forward 6
        down 5
        up 4
        down 7
        down 9
        up 9
        forward 7
        forward 4
        down 7
        down 5
        down 2
        down 9
        down 6
        down 7
        up 6
        up 7
        up 6
        down 4
        forward 9
        down 8
        down 7
        down 8
        down 4
        forward 5
        forward 1
        up 5
        forward 5
        forward 4
        down 3
        forward 8
        down 7
        down 9
        up 1
        down 1
        up 8
        up 6
        down 9
        up 9
        down 9
        forward 7
        down 3
        forward 6
        down 6
        forward 6
        down 9
        down 7
        up 1
        down 2
        up 2
        down 3
        down 1
        up 4
        forward 3
        down 3
        up 8
        down 3
        forward 3
        forward 6
        forward 6
        forward 6
        forward 7
        up 2
        forward 6
        forward 1
        up 4
        up 7
        down 5
        down 9
        forward 6
        down 4
        forward 6
        down 7
        down 2
        up 9
        up 3
        forward 8
        forward 5
        down 1
        down 6
        down 7
        down 5
        up 3
        up 9
        forward 2
        forward 5
        down 3
        down 2
        up 2
        forward 6
        forward 3
        down 8
        forward 7
        up 6
        forward 4
        down 8
        forward 6
        down 7
        forward 9
        forward 6
        forward 2
        forward 4
        up 5
        up 1
        forward 3
        forward 2
        up 3
        down 4
        down 3
        down 1
        up 8
        forward 6
        down 4
        down 9
        down 3
        up 8
        down 5
        forward 2
        down 3
        up 7
        down 3
        up 1
        up 1
        up 2
        up 1
        forward 4
        forward 1
        forward 4
        forward 3
        forward 8
        down 8
        up 5
        down 4
        down 4
        down 6
        down 9
        down 7
        forward 5
        forward 3
        up 3
        forward 6
        forward 5
        forward 2
        forward 6
        up 4
        forward 2
        up 3
        down 2
        forward 3
        down 8
        forward 1
        forward 2
        down 3
        down 5
        forward 6
        forward 3
        forward 6
        up 3
        forward 5
        forward 3
        forward 5
        down 6
        down 4
        down 4
        forward 3
        forward 3
        up 6
        up 8
        forward 5
        forward 1
        down 3
        down 8
        down 9
        up 3
        down 7
        forward 4
        forward 2
        down 2
        up 6
        down 1
        down 8
        forward 3
        up 1
        down 7
        down 7
        down 5
        forward 3
        down 8
        forward 3
        down 7
        down 5
        up 2
        forward 9
        down 8
        down 5
        forward 3
        forward 2
        forward 7
        up 8
        down 2
        down 5
        down 8
        down 9
        down 9
        down 1
        up 4
        forward 5
        up 1
        up 4
        forward 1
        down 1
        down 7
        up 9
        up 7
        down 5
        down 9
        down 9
        down 8
        forward 7
        down 3
        up 4
        down 7
        down 8
        forward 7
        forward 4
        up 9
        down 2
        up 7
        forward 5
        down 3
        forward 3
        forward 5
        forward 5
        down 2
        down 2
        down 7
        up 8
        up 9
        down 1
        forward 9
        forward 3
        up 3
        forward 9
        up 2
        down 7
        down 3
        forward 4
        down 5
        down 3
        up 5
        forward 4
    """.trimIndent().lines()
}
